-- MySQL Script generated by MySQL Workbench
-- Fri Apr 24 13:34:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema olhar-pedagogico-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema olhar-pedagogico-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `olhar-pedagogico-db` DEFAULT CHARACTER SET utf8 ;
USE `olhar-pedagogico-db` ;

-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t001_empr_inst_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t001_empr_inst_base` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX `chave_UNIQUE` (`id_empresa` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
