-- MySQL Script generated by MySQL Workbench
-- Mon Apr 27 13:35:50 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema olhar-pedagogico-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema olhar-pedagogico-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `olhar-pedagogico-db` DEFAULT CHARACTER SET utf8 ;
USE `olhar-pedagogico-db` ;

-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t001_empr_inst_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t001_empr_inst_base` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `ativo` TINYINT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX `chave_UNIQUE` (`id_empresa` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t002_unes_inst_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t002_unes_inst_base` (
  `id_unidade` INT NOT NULL AUTO_INCREMENT,
  `t001_id_empresa` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email_contato` VARCHAR(255) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_unidade`, `t001_id_empresa`),
  INDEX `fk_t002_unes_inst_base_t001_empr_inst_base_idx` (`t001_id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_t002_unes_inst_base_t001_empr_inst_base`
    FOREIGN KEY (`t001_id_empresa`)
    REFERENCES `olhar-pedagogico-db`.`t001_empr_inst_base` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t021_pess_pers_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t021_pess_pers_base` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(255) NULL,
  `telefone` VARCHAR(20) NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pessoa`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t022_alun_pers_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t022_alun_pers_base` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `t021_id_pessoa` INT NOT NULL,
  `nm_chamada` VARCHAR(255) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_aluno`, `t021_id_pessoa`),
  INDEX `fk_t022_alun_pers_base_t021_pess_pers_base1_idx` (`t021_id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_t022_alun_pers_base_t021_pess_pers_base1`
    FOREIGN KEY (`t021_id_pessoa`)
    REFERENCES `olhar-pedagogico-db`.`t021_pess_pers_base` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t024_pfun_eqpe_conf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t024_pfun_eqpe_conf` (
  `id_papel` INT NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(20) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `nivel_hierarquico` TINYINT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `t024_pfun_eqpe_confcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_papel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t023_func_eqpe_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t023_func_eqpe_base` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `t021_id_pessoa` INT NOT NULL,
  `t024_id_papel` INT NOT NULL,
  `nome_usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `ultimo_login` DATETIME NULL,
  `ativo` TINYINT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_funcionario`, `t021_id_pessoa`),
  UNIQUE INDEX `nome_usuario_UNIQUE` (`nome_usuario` ASC) VISIBLE,
  INDEX `fk_t023_func_eqpe_base_t021_pess_pers_base1_idx` (`t021_id_pessoa` ASC) VISIBLE,
  INDEX `fk_t023_func_eqpe_base_t024_pfun_eqpe_conf1_idx` (`t024_id_papel` ASC) VISIBLE,
  CONSTRAINT `fk_t023_func_eqpe_base_t021_pess_pers_base1`
    FOREIGN KEY (`t021_id_pessoa`)
    REFERENCES `olhar-pedagogico-db`.`t021_pess_pers_base` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t023_func_eqpe_base_t024_pfun_eqpe_conf1`
    FOREIGN KEY (`t024_id_papel`)
    REFERENCES `olhar-pedagogico-db`.`t024_pfun_eqpe_conf` (`id_papel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t041_turm_acad_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t041_turm_acad_base` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `t002_id_empresa` INT NOT NULL,
  `t002_id_unidade` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `ano_letivo` INT NOT NULL,
  `ativa` TINYINT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_turma`, `t002_id_empresa`, `t002_id_unidade`),
  INDEX `fk_t041_turm_acad_base_t002_unes_inst_base1_idx` (`t002_id_unidade` ASC, `t002_id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_t041_turm_acad_base_t002_unes_inst_base1`
    FOREIGN KEY (`t002_id_unidade` , `t002_id_empresa`)
    REFERENCES `olhar-pedagogico-db`.`t002_unes_inst_base` (`id_unidade` , `t001_id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t043_prtu_acad_link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t043_prtu_acad_link` (
  `t041_id_empresa` INT NOT NULL,
  `t041_id_unidade` INT NOT NULL,
  `t041_id_turma` INT NOT NULL,
  `t023_id_pessoa` INT NOT NULL,
  `t023_id_funcionario` INT NOT NULL,
  `professor_principal` TINYINT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`t041_id_empresa`, `t041_id_unidade`, `t041_id_turma`, `t023_id_pessoa`, `t023_id_funcionario`),
  INDEX `fk_t043_prtu_acad_link_t023_func_eqpe_base1_idx` (`t023_id_funcionario` ASC, `t023_id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_t043_prtu_acad_link_t041_turm_acad_base1`
    FOREIGN KEY (`t041_id_turma` , `t041_id_empresa` , `t041_id_unidade`)
    REFERENCES `olhar-pedagogico-db`.`t041_turm_acad_base` (`id_turma` , `t002_id_empresa` , `t002_id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t043_prtu_acad_link_t023_func_eqpe_base1`
    FOREIGN KEY (`t023_id_funcionario` , `t023_id_pessoa`)
    REFERENCES `olhar-pedagogico-db`.`t023_func_eqpe_base` (`id_funcionario` , `t021_id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
