-- MySQL Script generated by MySQL Workbench
-- Tue Apr 28 20:09:30 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema olhar-pedagogico-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema olhar-pedagogico-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `olhar-pedagogico-db` DEFAULT CHARACTER SET utf8 ;
USE `olhar-pedagogico-db` ;

-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t001_empr_inst_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t001_empr_inst_base` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `ativo` TINYINT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX `chave_UNIQUE` (`id_empresa` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t002_unes_inst_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t002_unes_inst_base` (
  `id_unidade` INT NOT NULL AUTO_INCREMENT,
  `t001_id_empresa` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email_contato` VARCHAR(255) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_unidade`, `t001_id_empresa`),
  INDEX `fk_t002_unes_inst_base_t001_empr_inst_base_idx` (`t001_id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_t002_unes_inst_base_t001_empr_inst_base`
    FOREIGN KEY (`t001_id_empresa`)
    REFERENCES `olhar-pedagogico-db`.`t001_empr_inst_base` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t021_pess_pers_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t021_pess_pers_base` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(255) NULL,
  `telefone` VARCHAR(20) NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pessoa`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t022_alun_pers_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t022_alun_pers_base` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `t021_id_pessoa` INT NOT NULL,
  `nm_chamada` VARCHAR(255) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_aluno`, `t021_id_pessoa`),
  INDEX `fk_t022_alun_pers_base_t021_pess_pers_base1_idx` (`t021_id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_t022_alun_pers_base_t021_pess_pers_base1`
    FOREIGN KEY (`t021_id_pessoa`)
    REFERENCES `olhar-pedagogico-db`.`t021_pess_pers_base` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t024_pfun_eqpe_conf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t024_pfun_eqpe_conf` (
  `id_papel` INT NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(20) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `nivel_hierarquico` TINYINT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `t024_pfun_eqpe_confcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_papel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t023_func_eqpe_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t023_func_eqpe_base` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `t021_id_pessoa` INT NOT NULL,
  `t024_id_papel` INT NOT NULL,
  `nome_usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `ultimo_login` DATETIME NULL,
  `ativo` TINYINT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_funcionario`, `t021_id_pessoa`),
  UNIQUE INDEX `nome_usuario_UNIQUE` (`nome_usuario` ASC) VISIBLE,
  INDEX `fk_t023_func_eqpe_base_t021_pess_pers_base1_idx` (`t021_id_pessoa` ASC) VISIBLE,
  INDEX `fk_t023_func_eqpe_base_t024_pfun_eqpe_conf1_idx` (`t024_id_papel` ASC) VISIBLE,
  CONSTRAINT `fk_t023_func_eqpe_base_t021_pess_pers_base1`
    FOREIGN KEY (`t021_id_pessoa`)
    REFERENCES `olhar-pedagogico-db`.`t021_pess_pers_base` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t023_func_eqpe_base_t024_pfun_eqpe_conf1`
    FOREIGN KEY (`t024_id_papel`)
    REFERENCES `olhar-pedagogico-db`.`t024_pfun_eqpe_conf` (`id_papel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t041_turm_acad_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t041_turm_acad_base` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `t002_id_empresa` INT NOT NULL,
  `t002_id_unidade` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `ano_letivo` INT NOT NULL,
  `ativa` TINYINT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modificacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_turma`, `t002_id_empresa`, `t002_id_unidade`),
  INDEX `fk_t041_turm_acad_base_t002_unes_inst_base1_idx` (`t002_id_unidade` ASC, `t002_id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_t041_turm_acad_base_t002_unes_inst_base1`
    FOREIGN KEY (`t002_id_unidade` , `t002_id_empresa`)
    REFERENCES `olhar-pedagogico-db`.`t002_unes_inst_base` (`id_unidade` , `t001_id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t043_prtu_acad_link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t043_prtu_acad_link` (
  `t041_id_empresa` INT NOT NULL,
  `t041_id_unidade` INT NOT NULL,
  `t041_id_turma` INT NOT NULL,
  `t023_id_pessoa` INT NOT NULL,
  `t023_id_funcionario` INT NOT NULL,
  `professor_principal` TINYINT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`t041_id_empresa`, `t041_id_unidade`, `t041_id_turma`, `t023_id_pessoa`, `t023_id_funcionario`),
  INDEX `fk_t043_prtu_acad_link_t023_func_eqpe_base1_idx` (`t023_id_funcionario` ASC, `t023_id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_t043_prtu_acad_link_t041_turm_acad_base1`
    FOREIGN KEY (`t041_id_turma` , `t041_id_empresa` , `t041_id_unidade`)
    REFERENCES `olhar-pedagogico-db`.`t041_turm_acad_base` (`id_turma` , `t002_id_empresa` , `t002_id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t043_prtu_acad_link_t023_func_eqpe_base1`
    FOREIGN KEY (`t023_id_funcionario` , `t023_id_pessoa`)
    REFERENCES `olhar-pedagogico-db`.`t023_func_eqpe_base` (`id_funcionario` , `t021_id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t042_aula_acad_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t042_aula_acad_base` (
  `id_aula` INT NOT NULL AUTO_INCREMENT,
  `t043_id_empresa` INT NOT NULL,
  `t043_id_unidade` INT NOT NULL,
  `t043_id_turma` INT NOT NULL,
  `t043_id_pessoa` INT NOT NULL,
  `t043_id_funcionario` INT NOT NULL,
  `data_hora_aula` DATETIME NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_aula`, `t043_id_empresa`, `t043_id_unidade`, `t043_id_turma`, `t043_id_pessoa`, `t043_id_funcionario`),
  INDEX `fk_t042_aula_acad_base_t043_prtu_acad_link1_idx` (`t043_id_empresa` ASC, `t043_id_unidade` ASC, `t043_id_turma` ASC, `t043_id_pessoa` ASC, `t043_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_t042_aula_acad_base_t043_prtu_acad_link1`
    FOREIGN KEY (`t043_id_empresa` , `t043_id_unidade` , `t043_id_turma` , `t043_id_pessoa` , `t043_id_funcionario`)
    REFERENCES `olhar-pedagogico-db`.`t043_prtu_acad_link` (`t041_id_empresa` , `t041_id_unidade` , `t041_id_turma` , `t023_id_pessoa` , `t023_id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t061_diar_educ_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t061_diar_educ_base` (
  `id_diario` INT NOT NULL AUTO_INCREMENT,
  `t042_id_aula` INT NOT NULL,
  `t042_id_empresa` INT NOT NULL,
  `t042_id_unidade` INT NOT NULL,
  `t042_id_turma` INT NOT NULL,
  `t042_id_pessoa` INT NOT NULL,
  `t042_id_funcionario` INT NOT NULL,
  `status_processamento` ENUM('AGUARDANDO_AUDIO', 'EM_TRANSCRICAO', 'PROCESSADO', 'ERRO') NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_diario`, `t042_id_aula`, `t042_id_empresa`, `t042_id_unidade`, `t042_id_turma`, `t042_id_pessoa`, `t042_id_funcionario`),
  INDEX `fk_t061_diar_educ_base_t042_aula_acad_base1_idx` (`t042_id_aula` ASC, `t042_id_empresa` ASC, `t042_id_unidade` ASC, `t042_id_turma` ASC, `t042_id_pessoa` ASC, `t042_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_t061_diar_educ_base_t042_aula_acad_base1`
    FOREIGN KEY (`t042_id_aula` , `t042_id_empresa` , `t042_id_unidade` , `t042_id_turma` , `t042_id_pessoa` , `t042_id_funcionario`)
    REFERENCES `olhar-pedagogico-db`.`t042_aula_acad_base` (`id_aula` , `t043_id_empresa` , `t043_id_unidade` , `t043_id_turma` , `t043_id_pessoa` , `t043_id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t044_altu_acad_link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t044_altu_acad_link` (
  `t041_id_empresa` INT NOT NULL,
  `t041_id_unidade` INT NOT NULL,
  `t041_id_turma` INT NOT NULL,
  `t022_id_pessoa` INT NOT NULL,
  `t022_id_aluno` INT NOT NULL,
  `status_matricula` ENUM('ATIVO', 'TRANSFERIDO', 'DESISTENTE', 'CONCLUIDO') NOT NULL,
  `data_ingresso` DATE NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`t041_id_empresa`, `t041_id_unidade`, `t041_id_turma`, `t022_id_pessoa`, `t022_id_aluno`),
  INDEX `fk_t044_altu_acad_link_t022_alun_pers_base1_idx` (`t022_id_aluno` ASC, `t022_id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_t044_altu_acad_link_t041_turm_acad_base1`
    FOREIGN KEY (`t041_id_turma` , `t041_id_empresa` , `t041_id_unidade`)
    REFERENCES `olhar-pedagogico-db`.`t041_turm_acad_base` (`id_turma` , `t002_id_empresa` , `t002_id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t044_altu_acad_link_t022_alun_pers_base1`
    FOREIGN KEY (`t022_id_aluno` , `t022_id_pessoa`)
    REFERENCES `olhar-pedagogico-db`.`t022_alun_pers_base` (`id_aluno` , `t021_id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t062_diau_educ_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t062_diau_educ_base` (
  `id_audio` INT NOT NULL AUTO_INCREMENT,
  `t061_id_diario` INT NOT NULL,
  `t061_id_aula` INT NOT NULL,
  `t061_id_empresa` INT NOT NULL,
  `t061_id_unidade` INT NOT NULL,
  `t061_id_turma` INT NOT NULL,
  `t061_id_pessoa` INT NOT NULL,
  `t061_id_funcionario` INT NOT NULL,
  `nome_bucket` VARCHAR(100) NOT NULL,
  `chave_objeto` VARCHAR(1024) NOT NULL,
  `tamanho_arquivo` BIGINT NOT NULL,
  `extencao` VARCHAR(10) NOT NULL,
  `duracao_segundos` INT NOT NULL,
  `checksum` VARCHAR(64) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_audio`, `t061_id_diario`, `t061_id_aula`, `t061_id_empresa`, `t061_id_unidade`, `t061_id_turma`, `t061_id_pessoa`, `t061_id_funcionario`),
  INDEX `fk_t062_diau_educ_base_t061_diar_educ_base1_idx` (`t061_id_diario` ASC, `t061_id_aula` ASC, `t061_id_empresa` ASC, `t061_id_unidade` ASC, `t061_id_turma` ASC, `t061_id_pessoa` ASC, `t061_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_t062_diau_educ_base_t061_diar_educ_base1`
    FOREIGN KEY (`t061_id_diario` , `t061_id_aula` , `t061_id_empresa` , `t061_id_unidade` , `t061_id_turma` , `t061_id_pessoa` , `t061_id_funcionario`)
    REFERENCES `olhar-pedagogico-db`.`t061_diar_educ_base` (`id_diario` , `t042_id_aula` , `t042_id_empresa` , `t042_id_unidade` , `t042_id_turma` , `t042_id_pessoa` , `t042_id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t063_tran_educ_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t063_tran_educ_base` (
  `id_transcricao` INT NOT NULL AUTO_INCREMENT,
  `t062_id_audio` INT NOT NULL,
  `t062_id_diario` INT NOT NULL,
  `t062_id_aula` INT NOT NULL,
  `t062_id_empresa` INT NOT NULL,
  `t062_id_unidade` INT NOT NULL,
  `t062_id_turma` INT NOT NULL,
  `t062_id_pessoa` INT NOT NULL,
  `t062_id_funcionario` INT NOT NULL,
  `transcricao` MEDIUMTEXT NOT NULL,
  `transcricao_json` LONGTEXT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_transcricao`, `t062_id_audio`, `t062_id_diario`, `t062_id_aula`, `t062_id_empresa`, `t062_id_unidade`, `t062_id_turma`, `t062_id_pessoa`, `t062_id_funcionario`),
  INDEX `fk_t063_tran_educ_base_t062_diau_educ_base1_idx` (`t062_id_audio` ASC, `t062_id_diario` ASC, `t062_id_aula` ASC, `t062_id_empresa` ASC, `t062_id_unidade` ASC, `t062_id_turma` ASC, `t062_id_pessoa` ASC, `t062_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_t063_tran_educ_base_t062_diau_educ_base1`
    FOREIGN KEY (`t062_id_audio` , `t062_id_diario` , `t062_id_aula` , `t062_id_empresa` , `t062_id_unidade` , `t062_id_turma` , `t062_id_pessoa` , `t062_id_funcionario`)
    REFERENCES `olhar-pedagogico-db`.`t062_diau_educ_base` (`id_audio` , `t061_id_diario` , `t061_id_aula` , `t061_id_empresa` , `t061_id_unidade` , `t061_id_turma` , `t061_id_pessoa` , `t061_id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t064_resi_educ_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t064_resi_educ_base` (
  `id_resumo` INT NOT NULL AUTO_INCREMENT,
  `t041_id_turma` INT NULL,
  `t041_id_empresa` INT NULL,
  `t041_id_unidade` INT NULL,
  `t042_id_aula` INT NULL,
  `t042_id_empresa` INT NULL,
  `t042_id_unidade` INT NULL,
  `t042_id_turma` INT NULL,
  `t042_id_pessoa` INT NULL,
  `t042_id_funcionario` INT NULL,
  `t022_id_aluno` INT NULL,
  `t022_id_pessoa` INT NULL,
  `tipo_resumo` ENUM('AULA', 'SEMANA', 'MES', 'ANO') NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `resumo_texto` MEDIUMTEXT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_resumo`),
  INDEX `fk_t064_resi_educ_base_t041_turm_acad_base1_idx` (`t041_id_turma` ASC, `t041_id_empresa` ASC, `t041_id_unidade` ASC) VISIBLE,
  INDEX `fk_t064_resi_educ_base_t022_alun_pers_base1_idx` (`t022_id_aluno` ASC, `t022_id_pessoa` ASC) VISIBLE,
  INDEX `fk_t064_resi_educ_base_t042_aula_acad_base1_idx` (`t042_id_aula` ASC, `t042_id_empresa` ASC, `t042_id_unidade` ASC, `t042_id_turma` ASC, `t042_id_pessoa` ASC, `t042_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_t064_resi_educ_base_t041_turm_acad_base1`
    FOREIGN KEY (`t041_id_turma` , `t041_id_empresa` , `t041_id_unidade`)
    REFERENCES `olhar-pedagogico-db`.`t041_turm_acad_base` (`id_turma` , `t002_id_empresa` , `t002_id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t064_resi_educ_base_t022_alun_pers_base1`
    FOREIGN KEY (`t022_id_aluno` , `t022_id_pessoa`)
    REFERENCES `olhar-pedagogico-db`.`t022_alun_pers_base` (`id_aluno` , `t021_id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t064_resi_educ_base_t042_aula_acad_base1`
    FOREIGN KEY (`t042_id_aula` , `t042_id_empresa` , `t042_id_unidade` , `t042_id_turma` , `t042_id_pessoa` , `t042_id_funcionario`)
    REFERENCES `olhar-pedagogico-db`.`t042_aula_acad_base` (`id_aula` , `t043_id_empresa` , `t043_id_unidade` , `t043_id_turma` , `t043_id_pessoa` , `t043_id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhar-pedagogico-db`.`t065_resa_educ_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhar-pedagogico-db`.`t065_resa_educ_base` (
  `id_audio` INT NOT NULL AUTO_INCREMENT,
  `t064_id_resumo` INT NOT NULL,
  `nome_bucket` VARCHAR(100) NOT NULL,
  `chave_objeto` VARCHAR(1024) NOT NULL,
  `duracao_segundos` INT NOT NULL,
  `formato` VARCHAR(10) NOT NULL,
  `tamanho_bytes` BIGINT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_audio`, `t064_id_resumo`),
  INDEX `fk_t065_resa_educ_base_t064_resi_educ_base1_idx` (`t064_id_resumo` ASC) VISIBLE,
  CONSTRAINT `fk_t065_resa_educ_base_t064_resi_educ_base1`
    FOREIGN KEY (`t064_id_resumo`)
    REFERENCES `olhar-pedagogico-db`.`t064_resi_educ_base` (`id_resumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
