services:

  backend-institucional-service:
    build:
      context: ../../backend-institucional-service
      dockerfile: Dockerfile
    profiles:
      - aplicacao
    container_name: backend-institucional-service
    restart: unless-stopped
    depends_on:
      vault:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "wget", "-q", "http://backend-institucional-service:8000/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  backend-pessoas-service:
    build:
      context: ../../backend-pessoas-service
      dockerfile: Dockerfile
    profiles:
      - aplicacao
    container_name: backend-pessoas-service
    restart: unless-stopped
    depends_on:
      vault:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - "8001:8001"
    env_file:
      - env-backend-pessoas-service
    healthcheck:
      test: ["CMD", "wget", "-q", "http://backend-pessoas-service:8001/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  backend-academico-service:
    build:
      context: ../../backend-academico-service
      dockerfile: Dockerfile
    profiles:
      - aplicacao
    container_name: backend-academico-service
    restart: unless-stopped
    depends_on:
      vault:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - "8002:8002"
    env_file:
      - env-backend-academico-service
    healthcheck:
      test: [ "CMD", "wget", "-q", "http://backend-academico-service:8002/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  backend-pedagogico-service:
    build:
      context: ../../backend-pedagogico-service
      dockerfile: Dockerfile
    profiles:
      - aplicacao
    container_name: backend-pedagogico-service
    restart: unless-stopped
    depends_on:
      vault:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - "8003:8003"
    env_file:
      - env-backend-pedagogico-service
    healthcheck:
      test: [ "CMD", "wget", "-q", "http://backend-pedagogico-service:8003/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  vault:
    image: hashicorp/vault:1.21
    container_name: vault
    profiles:
      - aplicacao
      - infraestrutura
    ports:
      - "8200:8200"
    volumes:
      - ./vault/data:/vault/data
      - ./vault/config:/vault/config
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: vault server -config=/vault/config/vault.hcl
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mysql:
    image: mysql:8.4.8
    profiles:
      - infraestrutura
      - aplicacao
    container_name: platform-core-db-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: platform_core_db
      MYSQL_USER: mateus
      MYSQL_PASSWORD: mateus

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mateus", "-pmateus"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

