services:

  backend-institucional-service:
    build:
      context: ../../backend-institucional-service
      dockerfile: Dockerfile
    container_name: backend-institucional-service
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mysql:
    image: mysql:8.4.8
    container_name: platform-core-db-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: platform_core_db
      MYSQL_USER: mateus
      MYSQL_PASSWORD: mateus

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mateus", "-pmateus"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

